# Generated by Django 3.2.7 on 2022-09-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShotDifficultyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=3)),
                ('age', models.IntegerField(default=0)),
                ('height_in', models.IntegerField(default=0)),
                ('weight_lb', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('early_2pa', models.IntegerField(default=0)),
                ('average_2pa', models.IntegerField(default=0)),
                ('late_2pa', models.IntegerField(default=0)),
                ('early_3pa', models.IntegerField(default=0)),
                ('average_3pa', models.IntegerField(default=0)),
                ('late_3pa', models.IntegerField(default=0)),
                ('rank_per_min_early_2pa', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_early_3pa', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_avg_2pa', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_avg_3pa', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_late_2pa', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_late_3pa', models.FloatField(default=0.0, null=True)),
                ('rank_open_3pa', models.FloatField(default=0.0, null=True)),
                ('rank_touch_2pa', models.FloatField(default=0.0, null=True)),
                ('rank_dribble_2pa', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
