# Generated by Django 3.2.7 on 2021-09-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=10)),
                ('player_id', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=3)),
                ('age', models.IntegerField(default=0)),
                ('height_in', models.IntegerField(default=0)),
                ('weight_lb', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('poss', models.FloatField(default=0.0)),
                ('usage_score', models.FloatField(default=0.0)),
                ('versatility_score', models.FloatField(default=0.0)),
                ('matchup_height', models.IntegerField(default=0)),
                ('matchup_weight', models.IntegerField(default=0)),
                ('poss_vs_lte75', models.FloatField(default=0.0)),
                ('poss_vs_lte78', models.FloatField(default=0.0)),
                ('poss_vs_lte81', models.FloatField(default=0.0)),
                ('poss_vs_gte82', models.FloatField(default=0.0)),
                ('freq_vs_lte75', models.FloatField(default=0.0)),
                ('freq_vs_lte78', models.FloatField(default=0.0)),
                ('freq_vs_lte81', models.FloatField(default=0.0)),
                ('freq_vs_gte82', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matchups.player')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, verbose_name='SEASON')),
                ('seconds', models.IntegerField(default=0, verbose_name='SECS')),
                ('possessions', models.FloatField(default=0.0, verbose_name='POSS')),
                ('two_pt_made', models.IntegerField(default=0, verbose_name='2PM')),
                ('two_pt_attempt', models.IntegerField(default=0, verbose_name='2PA')),
                ('three_pt_made', models.IntegerField(default=0, verbose_name='3PM')),
                ('three_pt_attempt', models.IntegerField(default=0, verbose_name='3PA')),
                ('free_throw_made', models.IntegerField(default=0, verbose_name='FTM')),
                ('free_throw_attempt', models.IntegerField(default=0, verbose_name='FTA')),
                ('assist', models.IntegerField(default=0, verbose_name='AST')),
                ('turnover', models.IntegerField(default=0, verbose_name='TOV')),
                ('defense_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_player', to='matchups.player')),
                ('offense_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offense_player', to='matchups.player')),
            ],
            options={
                'unique_together': {('offense_player', 'defense_player', 'season')},
            },
        ),
    ]
