# Generated by Django 3.2.7 on 2021-09-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='usage_score',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='versatility_score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
