# Generated by Django 3.2.7 on 2021-09-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defense_synergy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RimProtectionStat',
            new_name='DefensiveSynergyStat',
        ),
    ]
