# Generated by Django 3.2.7 on 2021-09-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense_synergy', '0002_rename_rimprotectionstat_defensivesynergystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensivesynergystat',
            name='spot_up_freq',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensivesynergystat',
            name='spot_up_percentile',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensivesynergystat',
            name='spot_up_poss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defensivesynergystat',
            name='spot_up_ppp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensivesynergystat',
            name='spot_up_pts',
            field=models.IntegerField(default=0),
        ),
    ]
