# Generated by Django 3.2.7 on 2022-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotchartstat',
            name='rank_per_min_atb_fga',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shotchartstat',
            name='rank_per_min_corner_fga',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shotchartstat',
            name='rank_per_min_floater_fga',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shotchartstat',
            name='rank_per_min_fta',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shotchartstat',
            name='rank_per_min_midrange_fga',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shotchartstat',
            name='rank_per_min_rim_fga',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
