# Generated by Django 3.2.7 on 2022-09-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=3)),
                ('age', models.IntegerField(default=0)),
                ('height_in', models.IntegerField(default=0)),
                ('weight_lb', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('fga', models.IntegerField(default=0)),
                ('fta', models.IntegerField(default=0)),
                ('rank_per_min_points', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_shot_attempts', models.FloatField(default=0.0, null=True)),
                ('rank_per_min_ts', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
