# Generated by Django 3.2.7 on 2021-09-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimProtectionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=3)),
                ('age', models.IntegerField(default=0)),
                ('height_in', models.IntegerField(default=0)),
                ('weight_lb', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('freq', models.FloatField(default=0.0)),
                ('def_fgm', models.IntegerField(default=0)),
                ('def_fga', models.IntegerField(default=0)),
                ('def_fg_pct', models.FloatField(default=0.0)),
                ('points_saved', models.FloatField(default=0.0)),
                ('def_fg_pct_score', models.FloatField(default=0.0, null=True)),
                ('points_saved_score', models.FloatField(default=0.0, null=True)),
                ('def_fgm_per_game', models.FloatField(default=0.0)),
                ('def_fga_per_game', models.FloatField(default=0.0)),
                ('points_saved_per_game', models.FloatField(default=0.0)),
                ('points_saved_per_game_score', models.FloatField(default=0.0, null=True)),
                ('def_fgm_per_min', models.FloatField(default=0.0)),
                ('def_fga_per_min', models.FloatField(default=0.0)),
                ('points_saved_per_min', models.FloatField(default=0.0)),
                ('points_saved_per_min_score', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
