# Generated by Django 3.2.7 on 2021-09-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_rebounding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReboundingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=3)),
                ('age', models.IntegerField(default=0)),
                ('height_in', models.IntegerField(default=0)),
                ('weight_lb', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('dreb', models.IntegerField(default=0)),
                ('dboxout', models.IntegerField(default=0)),
                ('dreb_rank', models.FloatField(default=0.0)),
                ('dboxout_rank', models.FloatField(default=0.0)),
                ('dreb_per_game', models.FloatField(default=0.0)),
                ('dboxout_per_game', models.FloatField(default=0.0)),
                ('dreb_rank_per_game', models.FloatField(default=0.0)),
                ('dboxout_rank_per_game', models.FloatField(default=0.0)),
                ('dreb_per_min', models.FloatField(default=0.0)),
                ('dboxout_per_min', models.FloatField(default=0.0)),
                ('dreb_rank_per_min', models.FloatField(default=0.0)),
                ('dboxout_rank_per_min', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.DeleteModel(
            name='RimProtectionStat',
        ),
    ]
