# Generated by Django 3.2.7 on 2021-09-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_playmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_blocks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_deals',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_deflections',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_steals',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_stocks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_blocks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_deals',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_deflections',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_steals',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_stocks',
            field=models.FloatField(default=0.0),
        ),
    ]
