# Generated by Django 3.2.7 on 2021-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_playmaking', '0003_auto_20210913_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='off_fouls_drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='other_fouls_drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_charges',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_off_fouls_drawn',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_other_fouls_drawn',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_shooting_fouls',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_charges',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_off_fouls_drawn',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_other_fouls_drawn',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_shooting_fouls',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defensiveplaymakingstat',
            name='shooting_fouls',
            field=models.IntegerField(default=0),
        ),
    ]
