# Generated by Django 3.2.7 on 2021-09-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_playmaking', '0004_auto_20210925_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensiveplaymakingstat',
            name='other_fouls_drawn',
        ),
        migrations.RemoveField(
            model_name='defensiveplaymakingstat',
            name='rank_per_game_other_fouls_drawn',
        ),
        migrations.RemoveField(
            model_name='defensiveplaymakingstat',
            name='rank_per_min_other_fouls_drawn',
        ),
    ]
